delays:
  repeat_delay: 0.2       # Segundos entre repeticiones individuales
  hold_threshold: 0.5     # Segundos para distinguir pulsación corta o larga

buttons:
  driver_up:
    pin: 17
    key: q
  driver_down:
    pin: 27
    key: w
  passenger_up:
    pin: 22
    key: e
  passenger_down:
    pin: 23
    key: r

combinations:
  short:
    driver_up+passenger_up: a
    driver_down+passenger_down: s
    driver_up+driver_down: d
    passenger_up+passenger_down: f

  long:
    driver_up+passenger_up: z
    driver_down+passenger_down: x
    driver_up+driver_down: c
    passenger_up+passenger_down: v
