# Acciones según combinaciones (máscaras)
# bit 1 -> drivers_up
# bit 2 -> drivers_down
# bit 3 -> passenger_up
# bit 4 -> passenger_down
# bit 5 -> is held
inputs:
  0b00001: DU
  0b00010: DD
  0b00100: PU
  0b01000: PD

  0b00101: DU+PU
  0b00110: DD+PU
  0b01001: DU+PD
  0b01010: DD+PD

  # HELD
  0b10001: H_DU
  0b10010: H_DD
  0b10100: H_PU
  0b11000: H_PD

  0b10101: H_DU+PU
  0b10110: H_DD+PU
  0b11001: H_DU+PD
  0b11010: H_DD+PD
 

## Este es innecesario pero da claridad a los mapeos
mappings:
  DU: next
  DD: prev
  PU: right
  PD: left
 
  DU+PU: home
  DD+PU: null
  DU+PD: null
  DD+PD: null 
  
  H_DU: toggle_playPause
  H_DD: toggle_playPause
  H_PU: back
  H_PD: selectDown
 
  H_DU+PU: null
  H_DD+PU: null
  H_DU+PD: null
  H_DD+PD: null

custom_actions:
  toggle_playPause: play_pause

actions:
  left: 'LEFT'
  right: 'RIGHT'
  selectDown: 'SPACE'
  back: 'BACKSPACE'
  down: 'DOWN' # No utilizado
  home: 'H'
  play: 'P'
  pause: 'O'
  next: 'M'
  prev: 'N'

